name: Build

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build
        run: |
          ./gradlew --no-daemon --warning-mode=all assembleRelease publishReleasePublicationToMavenLocal
          echo "commit=$(echo ${{ github.sha }} | cut -c-7)" >> $GITHUB_ENV

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: DchaUtilService@${{ env.commit }}
          path: svc/build/outputs/aar/svc-release.aar
