name: Build

on:
  push:
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set environment
        run: |
          {
            echo "group=$(grep POM_GROUP build.gradle | awk -F\" '{print $2}' | sed 's/\./\//g')"
            echo "id=$(grep POM_ID build.gradle | awk -F\" '{print $2}')"
            echo "version=$(grep POM_VERSION build.gradle | awk -F\" '{print $2}')"
            echo "commit=$(echo ${{ github.sha }} | cut -c-7)"
          } >> $GITHUB_ENV

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_SECRET }}" > secret.gpg
          gpg --import secret.gpg

      - name: Build
        run: |
          ./gradlew --no-daemon --warning-mode=all publishToMavenLocal

      - name: Packaging
        run: |
          cd ~/.m2/repository/${{ env.group }}/${{ env.id }}
          rm -f maven-metadata-local.xml
          cd ${{ env.version }}
          find . -maxdepth 1 -not -name "*.asc" -not -name "*.md5" -not -name "*.sha1" -type f -exec sh -c 'md5sum "$1" | awk "{print \$1}" > "$1.md5"' _ {} \;
          find . -maxdepth 1 -not -name "*.asc" -not -name "*.md5" -not -name "*.sha1" -type f -exec sh -c 'sha1sum "$1" | awk "{print \$1}" > "$1.sha1"' _ {} \;

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.id }}-${{ env.version }}@${{ env.commit }}
          path: ~/.m2/repository
